# Generated by Django 3.2.5 on 2023-01-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_users_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('amount', models.FloatField(default=100)),
                ('is_expired', models.BooleanField(default=False)),
                ('min_amount', models.IntegerField(default=500)),
            ],
        ),
    ]
