# Generated by Django 3.2.5 on 2023-01-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
