# Generated by Django 3.2.5 on 2023-01-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='Valid_from',
            new_name='valid_from',
        ),
    ]
